name: Sync from Upstream

on:
  # schedule:
  #   - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and sync
        env:
          PAT: ${{ secrets.UPSTREAM_PUSH_TOKEN }}
        run: |
          git remote add upstream https://x-access-token:${PAT}@github.com/baksho/temporal-uncertainty-aware-knowledge-graph.git
          git fetch upstream
          # git checkout main
          # git merge upstream/main --allow-unrelated-histories || true

      - name: Push back to fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/terriljoel/temporal-uncertainty-aware-knowledge-graph.git main

