name: Sync from Upstream1

on:
  # schedule:
  #   - cron: '30 */6 * * *'  # Slightly offset so they don't overlap
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Sync from upstream and push
        env:
          UPSTREAM_PAT: ${{ secrets.UPSTREAM_PUSH_TOKEN }}
        run: |
          git remote add upstream https://x-access-token:${UPSTREAM_PAT}@github.com/baksho/temporal-uncertainty-aware-knowledge-graph.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories || true
          git push origin main
